name    'dhgwilliam-dynenv'
version '0.0.1'
source 'UNKNOWN'
author 'dhgwilliam@gmail.com'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

dependency 'puppetlabs/vcsrepo'
dependency 'stahnma/epel'
